import type { RuleDefinition } from '@shopping-rescue/shared/types';

export const RULES_VERSION = '1.3.0';

export const CORE_RULES: RuleDefinition[] = [
  {
    id: 'SQ-001',
    version: 1,
    category: 'site_quality',
    title: 'Site not served over HTTPS',
    description: 'The storefront is not using HTTPS encryption.',
    severity: 'critical',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['url'],
    remediationTemplate: 'Enable SSL/TLS on your domain and redirect all HTTP traffic to HTTPS.',
    policyReference: 'https://support.google.com/merchants/answer/160037',
    enabled: true,
  },
  {
    id: 'SQ-002',
    version: 1,
    category: 'site_quality',
    title: 'Homepage returns error status',
    description: 'The homepage returned a 4xx or 5xx HTTP status code.',
    severity: 'critical',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['http_status'],
    remediationTemplate: 'Fix server errors on your homepage so it returns HTTP 200.',
    enabled: true,
  },
  {
    id: 'BI-001',
    version: 1,
    category: 'business_identity',
    title: 'Contact page not found',
    description: 'No accessible contact page was detected during the crawl.',
    severity: 'high',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Add a clear Contact page with email, phone, or contact form reachable from your footer.',
    enabled: true,
  },
  {
    id: 'BI-002',
    version: 1,
    category: 'business_identity',
    title: 'Privacy policy not found',
    description: 'No privacy policy page was detected.',
    severity: 'high',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate: 'Publish a privacy policy page and link it from your footer.',
    enabled: true,
  },
  {
    id: 'BI-003',
    version: 1,
    category: 'business_identity',
    title: 'Terms and conditions not found',
    description: 'No terms of service or legal terms page was detected.',
    severity: 'medium',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate: 'Add terms and conditions accessible from your site footer.',
    enabled: true,
  },
  {
    id: 'SH-001',
    version: 1,
    category: 'shipping',
    title: 'Shipping policy not found',
    description: 'No shipping or delivery policy page was detected.',
    severity: 'high',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Add a shipping policy describing costs, destinations, and delivery times.',
    enabled: true,
  },
  {
    id: 'RR-001',
    version: 1,
    category: 'returns_refunds',
    title: 'Returns policy not found',
    description: 'No returns or refund policy page was detected.',
    severity: 'high',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Publish a returns/refund policy with timeframe, process, and any fees.',
    enabled: true,
  },
  {
    id: 'PR-001',
    version: 1,
    category: 'products',
    title: 'Product missing price in structured data',
    description: 'A product page has JSON-LD Product data without a price.',
    severity: 'medium',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['json_ld'],
    remediationTemplate: 'Add accurate price and currency to your product structured data.',
    enabled: true,
  },
  {
    id: 'PR-002',
    version: 1,
    category: 'products',
    title: 'Product has thin description',
    description: 'A product has a very short or missing description.',
    severity: 'low',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['text'],
    remediationTemplate: 'Add a detailed, unique product description (at least 100 characters).',
    enabled: true,
  },
  {
    id: 'SQ-003',
    version: 1,
    category: 'site_quality',
    title: 'Important page returns error',
    description: 'A policy or key page returned a 4xx/5xx status.',
    severity: 'high',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['http_status', 'url'],
    remediationTemplate: 'Fix broken policy pages so they are accessible to customers.',
    enabled: true,
  },
  {
    id: 'TR-001',
    version: 1,
    category: 'trust_representation',
    title: 'Placeholder content detected',
    description: 'Lorem ipsum or template placeholder text found on the site.',
    severity: 'medium',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['text'],
    remediationTemplate: 'Replace all placeholder text with real business content.',
    enabled: true,
  },
  {
    id: 'SQ-004',
    version: 1,
    category: 'site_quality',
    title: 'robots.txt missing or unreachable',
    description: 'No robots.txt file was found or it could not be retrieved.',
    severity: 'info',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Publish a robots.txt file at your domain root to declare crawl preferences for search engines.',
    enabled: true,
  },
  {
    id: 'SQ-005',
    version: 1,
    category: 'site_quality',
    title: 'robots.txt blocks policy pages',
    description:
      'robots.txt disallows crawlers from important customer-facing policy or contact pages.',
    severity: 'medium',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Update robots.txt so contact, shipping, returns, and legal policy pages remain crawlable.',
    enabled: true,
  },
  {
    id: 'SQ-006',
    version: 1,
    category: 'site_quality',
    title: 'Overly restrictive robots.txt',
    description:
      'robots.txt blocks a large number of public URLs, which may limit search engine visibility.',
    severity: 'high',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Review robots.txt Disallow rules and avoid blocking product, collection, or policy URLs needed for Shopping visibility.',
    enabled: true,
  },
  {
    id: 'SQ-012',
    version: 1,
    category: 'site_quality',
    title: 'sitemap.xml missing or unreachable',
    description: 'No XML sitemap was found at common locations or via robots.txt.',
    severity: 'info',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Publish a sitemap.xml (or sitemap index) and reference it in robots.txt for better crawl coverage.',
    enabled: true,
  },
  {
    id: 'BI-004',
    version: 1,
    category: 'business_identity',
    title: 'About page not found',
    description: 'No about us or company information page was detected.',
    severity: 'medium',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Add an About page describing your business, mission, and who operates the store.',
    enabled: true,
  },
  {
    id: 'BI-005',
    version: 1,
    category: 'business_identity',
    title: 'No Organization structured data',
    description: 'No Organization or LocalBusiness JSON-LD was found on crawled pages.',
    severity: 'high',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['json_ld'],
    remediationTemplate:
      'Add Organization or LocalBusiness schema with business name, URL, and contact details.',
    enabled: true,
  },
  {
    id: 'BI-006',
    version: 1,
    category: 'business_identity',
    title: 'Contact page lacks reachable contact method',
    description: 'A contact page exists but no email address or phone number was detected in its content.',
    severity: 'medium',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['text'],
    remediationTemplate:
      'Display a customer support email or phone number on your contact page (not only a form).',
    enabled: true,
  },
  {
    id: 'SQ-007',
    version: 1,
    category: 'site_quality',
    title: 'Homepage title missing or generic',
    description: 'The homepage title tag is empty, very short, or uses a generic placeholder.',
    severity: 'medium',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['text'],
    remediationTemplate:
      'Set a descriptive homepage title with your brand name and what you sell.',
    enabled: true,
  },
  {
    id: 'SQ-008',
    version: 1,
    category: 'site_quality',
    title: 'Homepage meta description missing',
    description: 'The homepage has no meta description or it is too short to be useful.',
    severity: 'low',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['text'],
    remediationTemplate:
      'Add a unique meta description summarizing your store and value proposition (120–160 characters).',
    enabled: true,
  },
  {
    id: 'SQ-009',
    version: 1,
    category: 'site_quality',
    title: 'Homepage loads slowly',
    description: 'The homepage took longer than 3 seconds to respond during the scan.',
    severity: 'medium',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['response_time'],
    remediationTemplate:
      'Improve homepage performance — optimize images, reduce scripts, and review hosting/CDN.',
    enabled: true,
  },
  {
    id: 'SQ-010',
    version: 1,
    category: 'site_quality',
    title: 'Homepage missing language attribute',
    description: 'The homepage HTML lang attribute is missing.',
    severity: 'low',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['text'],
    remediationTemplate:
      'Set the html lang attribute on your theme (e.g. lang="en" or lang="fr") for accessibility and SEO.',
    enabled: true,
  },
  {
    id: 'TR-002',
    version: 1,
    category: 'trust_representation',
    title: 'FAQ page not found',
    description: 'No FAQ or help page was detected.',
    severity: 'low',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['url'],
    remediationTemplate:
      'Publish an FAQ addressing shipping, returns, sizing, and common pre-purchase questions.',
    enabled: true,
  },
  {
    id: 'TR-003',
    version: 1,
    category: 'trust_representation',
    title: 'Policy page has thin content',
    description: 'An important policy or contact page has very little visible text.',
    severity: 'medium',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['text'],
    remediationTemplate:
      'Expand policy pages with complete, customer-facing details — not just a single paragraph or link.',
    enabled: true,
  },
  {
    id: 'PR-003',
    version: 1,
    category: 'products',
    title: 'Product missing image in structured data',
    description: 'A product has JSON-LD Product data without an image.',
    severity: 'medium',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['json_ld'],
    remediationTemplate: 'Ensure each product has at least one image in structured data and on the page.',
    enabled: true,
  },
  {
    id: 'PR-004',
    version: 1,
    category: 'products',
    title: 'Product availability missing in structured data',
    description: 'A product JSON-LD block does not specify availability/in stock status.',
    severity: 'medium',
    confidenceMethod: 'deterministic',
    evidenceRequirements: ['json_ld'],
    remediationTemplate:
      'Add offers.availability (e.g. InStock / OutOfStock) to product structured data.',
    enabled: true,
  },
  {
    id: 'PR-005',
    version: 1,
    category: 'products',
    title: 'No products detected during crawl',
    description: 'The scan found product or collection pages but extracted no product structured data.',
    severity: 'high',
    confidenceMethod: 'heuristic',
    evidenceRequirements: ['json_ld'],
    remediationTemplate:
      'Verify products are published, indexable, and include Product JSON-LD with offers.',
    enabled: true,
  },
];
